# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308ea802919ea659f26ce523061c1b3800e700cfb6666ccf4ff268012eff4b343a06a36e846f7906f981569d081f686a6ec96e9518a92516ef1f4a071ae6e7b0

test:
  secret_key_base: 61aba8334d384330f2b6935a208166a3966733076475bd893c49295cb3889e52078094ed64a6610da03bad18fc074f5d1e8cce2058fe6aab93bd6ea8dbb870c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
